version: '3.3'
services:
  gateway-service:
    image: gateway-service:0.0.1
    container_name: gateway-service
    env_file: ./env/project.env
    restart: on-failure
    ports:
      - 8080:8080
  auth-service:
    image: auth-service:0.0.1
    container_name: auth-service
    env_file: ./java-env/project.env
    restart: on-failure
  system-service:
    image: system-service:0.0.1
    container_name: system-service
    env_file: ./java-env/project.env
    restart: on-failure
  file-service:
    image: file-service:0.0.1
    container_name: file-service
    env_file: ./java-env/project.env
    restart: on-failure
  message-service:
    image: message-service:0.0.1
    container_name: message-service
    env_file: ./java-env/project.env
    restart: on-failure
  bpm-service:
    image: bpm-service:0.0.1
    container_name: bpm-service
    env_file: ./java-env/project.env
    volumes:
      - ./data/bpm:/usr/share/fonts
    restart: on-failure
  business-service:
    image: business-service:0.0.1
    container_name: business-service
    env_file: ./java-env/project.env
    restart: on-failure

  job-client:
    image: job-client:0.0.1
    container_name: job-client
    env_file: ./java-env/project.env
    restart: on-failure
    ports:
      - 8090:8080
  job-service:
    image: job-service:0.0.1
    container_name: job-service
    env_file: ./java-env/project.env
    restart: on-failure
  vue-supply:
    image: vue-supply:0.0.1
    container_name: vue-supply
    volumes:
      - ./vue-env/env.js:/usr/share/nginx/html/env.js
    restart: on-failure
    ports:
      - 9528:80

