spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1


gateway:
  thread:
    pool:
      corePoolSize: 4
      maxPoolSize: 4
      keepAliveSeconds: 60
      queueCapacity: 1000
      threadNamePrefix: customer-task
  ignore:
    whites:
      - /auth/**
      - /system/druid/**
      - /system/login/loginForPwd
      - /system/login/generateCaptcha
      - /system/tenant/getTenantList
      - /file/druid/**
      - /file/attachment/downloadByParams
      - /file/attachment/upload
      - /message/websocket/**
      - /message/druid/**
  xss:
    enabled: true
    excludeUrls:
      - /workflow/definition/saveOrUpdate

