version: '2'
services:
  nacos:
    image: nacos/nacos-server:v2.1.0
    environment:
      # 支持主机名可以使用hostname,否则使用ip，默认ip
      - PREFER_HOST_MODE=ip
      # 单机模式
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/conf:/home/nacos/conf
    ports:
      - 8848:8848
    restart: always
    depends_on:
      - mysql
  redis:
    image: redis:5.0.0
    container_name: redis
    command: redis-server --port 6379  --appendonly yes --requirepass "123456"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: always
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/files:/var/lib/mysql-files
      - ./mysql/data:/var/lib/mysql
    restart: always
